# Generated by Django 5.0 on 2023-12-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_adi', models.CharField(max_length=200)),
                ('fatura_tarihi', models.DateField()),
                ('odeme_tarihi', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturalar', to='satis.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif_adi', models.CharField(max_length=200)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_gecerlilik_tarihi', models.DateField()),
                ('detaylar', models.TextField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='satis.firma')),
            ],
        ),
    ]
